---
- name: Ensure config dir
  become: yes
  become_user: root
  file:
    path: "{{ postgres_exporter_config_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure postgres exporter postgres_exporter conf file
  become: yes
  become_user: root
  template:
    src: postgres_exporter.yml.j2
    dest: "{{ postgres_exporter_config_dir }}/postgres_exporter.yml"
    owner: root
    mode: 0644
  notify:
    - Restart postgres exporter
    - Restart postgres exporter container

- name: Ensure postgres exporter postgres_exporter queries file
  become: yes
  become_user: root
  template:
    src: queries.yml.j2
    dest: "{{ postgres_exporter_config_dir }}/queries.yml"
    owner: root
    mode: 0644
  tags: test
  notify:
    - Restart postgres exporter
    - Restart postgres exporter container

- name: Include docker-related tasks
  include_tasks: run_in_docker.yml
  when: (postgres_exporter_run_in_docker)or(postgres_exporter_run_hybrid)
  loop: "{{ postgres_exporter_docker_services }}"
  loop_control:
    loop_var: postgres_exporter_service

- name: Include standalone tasks
  include_tasks: run_standalone.yml
  when: (not postgres_exporter_run_in_docker)or(postgres_exporter_run_hybrid)
